Servo function upgrade.
veRYANgry/SpiderBot pull request #2
Opened 2017-06-07 05:20 UTC by veRYANgry

2017-06-07 16:55 UTC, Jdban requested changes
Autoformat yo code pls. Spacing is terrible

2017-06-07 16:55 UTC, Jdban commented on SpiderBot.c
> +void setServoAmount(const i2c *eeBus, uint16_t rotation, uint8_t location);
I would suggest a more descriptive name

2017-06-07 16:55 UTC, Jdban commented on SpiderBot.c
> +// Set the servo from 0 to 180 degrees.
I feel like comments for method description should be more javadocs style

/*
 *
 */

2017-06-07 17:09 UTC, veRYANgry commented on SpiderBot.c
> +// Set the servo from 0 to 180 degrees.
Will add using the following style for doxygen:
/** Brief description which ends at this dot. Details follow
 *  here.
 */

2017-07-03 01:24 UTC, Jdban commented
Merge conflict somehow btw :P

2017-09-25 00:56 UTC, closed without merging